'use client'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { supabase } from '@/lib/supabase'

type Notice={id:string;event_type:string;title:string;body:string|null;entity_type:string|null;entity_id:string|null;is_read:boolean;created_at:string}
const labels:Record<string,string>={supplier_created:'مورد جديد',recommendation_created:'ترشيح جديد',feedback_created:'تقييم جديد',question_created:'طلب مورد جديد',report_created:'بلاغ جديد',claim_created:'طلب إثبات مورد'}
export default function AdminPage(){const router=useRouter();const [loading,setLoading]=useState(true);const [denied,setDenied]=useState(false);const [notices,setNotices]=useState<Notice[]>([]);const [stats,setStats]=useState({suppliers:0,questions:0,recommendations:0,feedback:0,reports:0});
 useEffect(()=>{let channel:any;(async()=>{const {data:a}=await supabase.auth.getUser();if(!a.user){router.replace('/login?next=/admin');return}const {data:p}=await supabase.from('profiles').select('account_type').eq('id',a.user.id).single();if(p?.account_type!=='admin'){setDenied(true);setLoading(false);return}await refresh();channel=supabase.channel('admin-notifications').on('postgres_changes',{event:'INSERT',schema:'public',table:'admin_notifications'},()=>refresh()).subscribe();setLoading(false)})();return()=>{if(channel)supabase.removeChannel(channel)}},[router]);
 async function refresh(){const [n,s,q,r,f,rep]=await Promise.all([supabase.from('admin_notifications').select('*').order('created_at',{ascending:false}).limit(50),supabase.from('suppliers').select('*',{count:'exact',head:true}),supabase.from('questions').select('*',{count:'exact',head:true}),supabase.from('recommendations').select('*',{count:'exact',head:true}),supabase.from('supplier_feedback').select('*',{count:'exact',head:true}),supabase.from('supplier_reports').select('*',{count:'exact',head:true}).eq('status','pending')]);setNotices((n.data??[]) as Notice[]);setStats({suppliers:s.count??0,questions:q.count??0,recommendations:r.count??0,feedback:f.count??0,reports:rep.count??0})}
 async function markRead(id:string){await supabase.from('admin_notifications').update({is_read:true}).eq('id',id);setNotices(x=>x.map(n=>n.id===id?{...n,is_read:true}:n))}
 if(loading)return <main className="adminShell"><div className="adminLoading">جاري تحميل لوحة التحكم...</div></main>;if(denied)return <main className="adminShell"><div className="adminLoading"><h2>هذه الصفحة للإدارة فقط</h2><a href="/">العودة للرئيسية</a></div></main>;
 const unread=notices.filter(n=>!n.is_read).length;return <main className="adminShell"><aside className="adminSide"><a className="logo adminLogo" href="/"><span className="logoMark">M</span><span><b>MNYRD</b><small>ADMIN</small></span></a><nav><a className="selected">▦ لوحة التحكم</a><a>♙ الموردون</a><a>▤ طلبات الموردين</a><a>★ الترشيحات والتقييمات</a><a>⚑ البلاغات</a><a>⚙ الإعدادات</a></nav></aside><section className="adminMain"><header className="adminTop"><div><h1>لوحة التحكم</h1><p>متابعة نشاط مجتمع MNYRD لحظة بلحظة</p></div><div className="bell">♢<b>{unread}</b></div></header><div className="adminStats"><div><span>الموردون</span><strong>{stats.suppliers}</strong></div><div><span>طلبات الموردين</span><strong>{stats.questions}</strong></div><div><span>الترشيحات</span><strong>{stats.recommendations}</strong></div><div><span>التقييمات</span><strong>{stats.feedback}</strong></div><div className="alertStat"><span>بلاغات تنتظر المراجعة</span><strong>{stats.reports}</strong></div></div><div className="adminPanel"><div className="adminPanelHead"><div><h2>مركز الإشعارات</h2><p>المستجدات من الموردين والترشيحات والتقييمات والطلبات</p></div><span className="unreadBadge">{unread} غير مقروء</span></div><div className="noticeList">{notices.length===0?<div className="noNotices">لا توجد إشعارات حتى الآن.</div>:notices.map(n=><button onClick={()=>markRead(n.id)} className={`notice ${n.is_read?'read':''}`} key={n.id}><i>{n.event_type.includes('feedback')?'★':n.event_type.includes('supplier')?'♙':n.event_type.includes('report')?'⚑':'▤'}</i><div><b>{labels[n.event_type]||n.title}</b><span>{n.body||n.title}</span><small>{new Date(n.created_at).toLocaleString('ar-SA')}</small></div>{!n.is_read&&<em/>}</button>)}</div></div></section></main>}
